openapi: 3.1.0
info:
  version: 1.0.0
  title: Water track
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Application for monitoring water consumption
tags:
  - name: Authentication
    description: Operations about Authentication.
  - name: Common
    description: Getting general information
servers:
  - url: http://localhost:3002
  - url: https://warettrack.onrender.com
paths:
  /api/auth/register:
    post:
      $ref: ../swagger/paths/user/registerPost.yaml
  /api/auth/login:
    post:
      $ref: ../swagger/paths/user/loginPost.yaml
  /api/auth/current:
    get:
      $ref: ../swagger/paths/user/currentGet.yaml
  /api/auth/update-current-user:
    patch:
      $ref: ../swagger/paths/user/updateCurrentUserPatch.yaml
  /api/auth/logout:
    post:
      $ref: ../swagger/paths/user/logoutPost.yaml
  /api/auth/refresh:
    post:
      $ref: ../swagger/paths/user/refreshPost.yaml
  /api/auth/users-count:
    get:
      $ref: ../swagger/paths/common/countUsersGet.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
