openapi: 3.1.0
info:
  version: 1.0.0
  title: Water track
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Application for monitoring water consumption
tags:
  - name: Authentication
    description: Operations about Authentication.
  - name: User
    description: Operations about User.
  - name: Common
    description: Getting general information
  - name: Water
    description: Operations about Water.
servers:
  - url: https://watertrack.onrender.com
paths:
  /api/auth/register:
    post:
      $ref: ../swagger/paths/authentication/registerPost.yaml
  /api/auth/login:
    post:
      $ref: ../swagger/paths/authentication/loginPost.yaml
  /api/auth/logout:
    post:
      $ref: ../swagger/paths/authentication/logoutPost.yaml
  /api/auth/refresh:
    post:
      $ref: ../swagger/paths/authentication/refreshPost.yaml
  /api/auth/request-reset-email:
    post:
      $ref: ../swagger/paths/authentication/requestResetEmail.yaml
  /api/auth/reset-password:
    post:
      $ref: ../swagger/paths/authentication/resetPassword.yaml
  /api/auth/current:
    get:
      $ref: ../swagger/paths/user/currentGet.yaml
  /api/auth/update-current-user:
    patch:
      $ref: ../swagger/paths/user/updateCurrentUserPatch.yaml
  /api/users-count:
    get:
      $ref: ../swagger/paths/common/countUsersGet.yaml
  /api/water:
    post:
      $ref: ../swagger/paths/water/{id}/createWaterPost.yaml
  /api/water/{waterId}:
    # get:
    #   $ref: ../swagger/paths/water/{id}/getWaterById.yaml
    patch:
      $ref: ../swagger/paths/water/{id}/updateWaterByIdPatch.yaml
    delete:
      $ref: ../swagger/paths/water/{id}/deleteRecordById.yaml
  /api/water/day/{date}:
    get:
      $ref: ../swagger/paths/water/{id}/getWaterPerDay.yaml
  /api/water/month/{date}:
    get:
      $ref: ../swagger/paths/water/{id}/getWaterPerMonth.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security: []
